# Generated by Django 3.1.14 on 2022-10-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_auto_20221009_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonentity',
            name='description',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
