# Generated by Django 3.1.14 on 2022-10-09 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0007_auto_20221009_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='from_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokemon_entities.pokemon'),
        ),
    ]
