# Generated by Django 3.1.14 on 2022-10-09 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0008_pokemon_from_evolution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='from_evolution',
            new_name='evolution_from',
        ),
    ]
